import os
import json
import yaml
import wandb
import logging

from typing import cast, Optional, Literal
from dataclasses import dataclass, field

from transformers import HfArgumentParser


logger = logging.getLogger(__name__)


SUPPORTED_TRAINING_TASKS = ("image_classification", "model_adapters",)
OUTPUT_DIR_ARG = "output_dir"

@dataclass
class SweepArguments:
    """
    Arguments pertaining to how a hyperparameter search will be conducted.
    """

    training_task: Literal[*SUPPORTED_TRAINING_TASKS] = field( # type: ignore
        metadata={
            "help": f"Task name that specifies which training script is used. Currently supported options are {SUPPORTED_TRAINING_TASKS}."
        }
    )
    wandb_project: str = field(
        metadata={"help": "The name of the project where W&B runs created from the sweep are sent to."},
    )
    sweep_id: Optional[str] = field(
        default=None,
        metadata={
            "help": (
                "The unique identifier for a sweep. A sweep ID is generated by W&B CLI or Python SDK. "
                "This parameter is useful for distributed (parallel) launching of a hyperparameter search agents. "
                "If filled it overrides creation of new sweep and coordinates with existing one in W&B."
            )
        }
    )
    sweep_config_path: Optional[str] = field(
        default=None,
        metadata={
            "help": (
                "The path to configuration of a hyperparameter search. "
                "Must be to JSON that is a dictionary that conforms to the W&B sweep config spec."
            )
        }
    )
    runs_count: Optional[int] = field(
        default=None,
        metadata={
            "help": (
                "The number of sweep config trials to try.\n"
                "WARNING: Default is `None` which means that agent will try to run every possible combination of "
                "searched hyperparameters. This can be finete (large) or 'infinite' number of runs.\n"
                "Agent can be stopped at any time using W&B UI or CLI:\n"
                "   - Graceful stop: `wandb sweep --stop entity/project/sweep_ID`\n"
                "   - Force cancel: `wandb sweep --cancel entity/project/sweep_ID`"
            )
        }
    )


def run_sweep(sweep_args: SweepArguments):
    logger.info(f"Initializing a hyperparameter search for task {sweep_args.training_task} ...")
    if sweep_args.training_task == "image_classification":
        from image_classification.run_image_classification import main
    elif sweep_args.training_task == "model_adapters":
        from model_adapters.run_model_adapters_training import main
    else:
        raise ValueError(
            f"In sweep arguments you must provide valid and supported task. Currently available tasks:\n{SUPPORTED_TRAINING_TASKS}"
        )

    if sweep_args.sweep_id is None and sweep_args.sweep_config_path is not None:
        logger.info(f"\t> Creating new sweep with config {sweep_args.sweep_config_path}")
        assert os.path.isfile(sweep_args.sweep_config_path), "Provided path to sweep config is not valid"
        if sweep_args.sweep_config_path.endswith(".json"):
            with open(sweep_args.sweep_config_path, "r") as f:
                sweep_configuration = json.load(f)
        elif sweep_args.sweep_config_path.endswith(".yaml") or sweep_args.sweep_config_path.endswith(".yml"):
            with open(sweep_args.sweep_config_path, "r") as f:
                sweep_configuration = yaml.safe_load(f)
        else:
            raise ValueError("Sweep configuration must be JSON or YAML file")

        sweep_id = wandb.sweep(sweep=sweep_configuration, project=sweep_args.wandb_project)
        logger.info(f"\t> Sweep created with ID: {sweep_id}")
    elif sweep_args.sweep_id is not None:
        sweep_id = sweep_args.sweep_id
        logger.info(f"\t> Connecting to existing sweep with ID: {sweep_id}")
    else:
        raise ValueError(
            f"Missing specified `sweep_config_path` XOR `sweep_id` in launch arguments."
        )

    def run_builder():
        run = wandb.init()

        if OUTPUT_DIR_ARG in run.config:
            # Modify output directory path so that as sweep continues models are not overwritten
            run.config.update_locked(
                {
                    OUTPUT_DIR_ARG: f"{run.config[OUTPUT_DIR_ARG].rstrip(os.path.sep)}-{run.id}"
                },
                _allow_val_change=True
            )

        args = run.config.as_dict()
        logger.debug(f"Launching run {run.id} with args:\n{args}")
        return main(
            args=args
        )

    logger.info(f"Launching sweep {sweep_id} with {sweep_args.runs_count} run(s) ...")
    wandb.agent(
        sweep_id=sweep_id,
        function=run_builder,
        project=sweep_args.wandb_project,
        count=sweep_args.runs_count
    )


if __name__ == "__main__":
    parser = HfArgumentParser(SweepArguments)
    sweep_args = cast(
        SweepArguments,
        parser.parse_args_into_dataclasses()[0]
    )

    run_sweep(sweep_args=sweep_args)