import os
import json
import wandb
import logging

from typing import cast, Optional, Literal
from dataclasses import dataclass, field

from transformers import HfArgumentParser


logger = logging.getLogger(__name__)


SUPPORTED_TRAINING_TASKS = ("image_classification",)

@dataclass
class SweepArguments:
    """
    Arguments pertaining to how a hyperparameter search will be conducted.
    """

    training_task: Literal[*SUPPORTED_TRAINING_TASKS] = field( # type: ignore
        metadata={
            "help": "Task name that specifies which training script is used."
        }
    )
    sweep_id: Optional[str] = field(
        default=None,
        metadata={
            "help": (
                "The unique identifier for a sweep. A sweep ID is generated by W&B CLI or Python SDK. "
                "This parameter is useful for distributed (parallel) launching of a hyperparameter search agents. "
                "If filled it overrides creation of new sweep and coordinates with existing one in W&B."
            )
        }
    )
    sweep_config_path: Optional[str] = field(
        default=None,
        metadata={
            "help": (
                "The path to configuration of a hyperparameter search. "
                "Must be to JSON that is a dictionary that conforms to the W&B sweep config spec."
            )
        }
    )
    wandb_project: Optional[str] = field(
        default=None,
        metadata={
            "help": (
                "The name of the project where W&B runs created from the sweep are sent to. "
                "If the project is not specified, the run is sent to a project labeled 'Uncategorized'."
            )
        },
    )
    runs_count: Optional[int] = field(
        default=None,
        metadata={
            "help": (
                "The number of sweep config trials to try.\n"
                "WARNING: Default is `None` which means that agent will try to run every possible combination of "
                "searched hyperparameters. This can be finete (large) or 'infinite' number of runs.\n"
                "Agent can be stopped at any time using W&B UI or CLI:\n"
                "   - Graceful stop: `wandb sweep --stop entity/project/sweep_ID`\n"
                "   - Force cancel: `wandb sweep --cancel entity/project/sweep_ID`"
            )
        }
    )


if __name__ == "__main__":
    parser = HfArgumentParser(SweepArguments)
    sweep_args = cast(
        SweepArguments,
        parser.parse_args_into_dataclasses()[0]
    )

    logger.info(f"Initializing a hyperparameter search for task {sweep_args.training_task} ...")
    if sweep_args.training_task == "image_classification":
        from image_classification.run_image_classification import main
    else:
        raise ValueError(
            f"In sweep arguments you must provide valid and supported task. Currently available tasks:\n{SUPPORTED_TRAINING_TASKS}"
        )

    if sweep_args.sweep_id is None and sweep_args.sweep_config_path is not None:
        logger.info(f"\t> Creating new sweep with config {sweep_args.sweep_config_path}")
        assert os.path.isfile(sweep_args.sweep_config_path) and sweep_args.sweep_config_path.endswith(".json"), "Provided path to sweep config is not valid or is not JSON file."
        with open(sweep_args.sweep_config_path, "r") as f:
            sweep_configuration = json.load(f)

        sweep_id = wandb.sweep(sweep=sweep_configuration, project=sweep_args.wandb_project)
        logger.info(f"\t> Sweep created with ID: {sweep_id}")
    elif sweep_args.sweep_id is not None:
        sweep_id = sweep_args.sweep_id
        logger.info(f"\t> Connecting to existing sweep with ID: {sweep_id}")
    else:
        raise ValueError(
            f"Missing specified `sweep_config_path` XOR `sweep_id` in launch arguments."
        )

    logger.info(f"Launching sweep {sweep_id} with {sweep_args.runs_count} run(s) ...")
    wandb.agent(sweep_id=sweep_id, function=main, count=sweep_args.runs_count)