name: Sweep-GoogleHybridViT-Seesaw
method: bayes
metric:
  goal: minimize
  name: eval/loss
parameters:
  # Model:
  model_name_or_path:
    value: "/storage/plzen4-ntis/home/sulcm01/outputs/google_hybrid_vit/base"
  fp16:
    value: True
  # Dataset:
  dataset_name:
    value: "metacentrum_scratch/SpilledMILK10k"
  image_column_name:
    value: "image"
  label_column_name:
    value: "label"
  remove_unused_columns:
    value: False
  # Training:
  classification_task:
    value: "multiclass"
  output_dir:
    value: "/storage/plzen4-ntis/home/sulcm01/outputs/google_hybrid_vit/melanet_hvit_seesaw"
  overwrite_output_dir:
    value: True
  save_steps:
    value: 5000
  save_total_limit:
    value: 2
  load_best_model_at_end:
    value: True
  metric_for_best_model:
    value: "eval_loss"
  greater_is_better:
    value: False
  logging_strategy:
    value: "steps"
  logging_steps:
    value: 100
  do_train:
    value: True
  do_eval:
    value: True
  report_to:
    value: "wandb"
  dataloader_num_workers:
    value: 4
  seed:
    value: 42
  # Hyperparameters:
  num_train_epochs:
    value: 30
  learning_rate:
    min: 1e-5
    max: 1e-2
    distribution: log_uniform_values
  lr_scheduler_type:
    value: "cosine"
  warmup_ratio:
    value: 0.05
  seesaw_loss_multiplier:
    value: 1.0
  per_device_train_batch_size:
    values: [32, 64]
  gradient_accumulation_steps:
    value: 1
  per_device_eval_batch_size:
    value: 32
  eval_strategy:
    value: "steps"
  eval_steps:
    value: 500
  save_strategy:
    value: "steps"