python run_model_adapters_training.py \
    --adapter_output_path /home/sulcm/models/melanet/adapters/test_ViT_base_ResNet50_fusion_attn_aug.pt \
    --adapter_type fusion \
    --adapter_config "{\"in_features\":[768,2048],\"out_features\":11,\"use_attn\":true,\"attn_num_heads\":2,\"dropout\":0.1,\"modality_dropout\":0.05,\"drop_path_rate\":0.1}" \
    --model_name_or_path "/home/sulcm/models/melanet/vit_base/melanet_vit_base_fine_grid-dxjjru4m" \
    --zero_shot_model_name_or_path "/home/sulcm/models/melanet/resnet50/melanet_resnet50_fine_grid-n5511yzn" \
    --zero_shot_config "model_backend=hf" \
    --dataset_name /home/sulcm/datasets/milk10k/SpilledMILK10k \
    --feature_column_names image \
    --label_column_name label \
    --task multiclass \
    --remove_unused_columns False \
    --overwrite_output_dir \
    --num_train_epochs 1 \
    --apply_augmentations_prob 0.5 \
    --learning_rate 2e-6 \
    --lr_scheduler_type constant \
    --weight_decay 1e-5 \
    --per_device_train_batch_size 128 \
    --per_device_eval_batch_size 256 \
    --gradient_accumulation_steps 1 \
    --logging_strategy steps \
    --logging_steps 5 \
    --eval_strategy steps \
    --eval_steps 10 \
    --save_strategy steps \
    --save_steps 5000 \
    --save_total_limit 2 \
    --load_best_model_at_end True \
    --metric_for_best_model eval_loss \
    --greater_is_better False \
    --do_train \
    --do_eval \
    --fp16 \
    --report_to "none" \
    --logging_dir ./tensorboard_logs/Fusion-Attn-Adapters-Aug \
    --dataloader_num_workers 4 \
    --seed 42